### ISSUE TITLE
Need Code Highlight

### ISSUE THREAD

**Issue by joelcardinal** [looeee/discoverthree.com-examples#1]
Sorry, I don't Twitter, this issue is related to your book not the code but I couldn't find it's repo.

On page:
https://discoverthreejs.com/book/1-first-steps/7-load-models/#position-camera

You need to highlight that you also changed this line:
`camera = new THREE.PerspectiveCamera( 35, container.clientWidth / container.clientHeight, 1, 1000 );`

Otherwise the objects won't be within the frustum, even if they set the camera back.

Just finished going through your preview, eagerly awaiting your finished book.  I'd also be interested in a more advanced book after this introductory one, and/or, a living document that kept abreast with updates to Three.js.  Keep on Rockin!

**Comment by looeee** [comment]
Hey Joel,

Thanks for getting in touch, feedback is much appreciated. I'll fix that
ASAP :)

>  a living document that kept abreast with updates to Three.js

That's the idea - all the examples use the latest version of three.js
directly from the github CDN, so they'll always be up to date. Well, there
might be a day or two lag whenever a new version comes out, but I follow
the development of three.js pretty closely so I should usually get them
updated immediately.

You keep on rockin too :D

Lewy

**Comment by looeee** [comment]
Fixed!
